### PR TITLE
Support multiple rule paths as parameters

### LINKED ISSUE #4: Support multiple source folders
I'd like to be able to have two separate source folders for alerts, for example `base-rules/` and `custom-rules/`, to keep my overrides separate from the rules they override.

In the current implementation I don't think this is possible - alert-overrider only accepts one folder as an argument, and `ioutil.ReadDir` doesn't recurse.

I'd be happy to file a PR to add this.

### PR DESCRIPTION
**Pull request by markspolakovs**
This PR adds support for passing multiple directories with rules, to enable overrides to be better organised. They are all merged together as if they were in one directory.

Resolves #4.

### CODE REVIEW

**Comment by markspolakovs** [comment]
Actually, on second thought a more future-proof approach could be to use filepath.Glob, as this would allow for more customisability of the path matching. What do you think @martinhaus?

**Comment by martinhaus** [comment]
I think it's a good idea to use `filepath.Glob`. I'd still allow specifying multiple paths as in your original concept though.

**Comment by markspolakovs** [comment]
Updated - though I did realise that this may technically be a breaking change (because I don't think `examples/` would match the files in `examples` - could be wrong though!). Not sure what's the best way to handle it - perhaps a flag to enable "glob mode"?

**Comment by martinhaus** [comment]
Got it. So we would have to do something like
```
./prometheus_alert_overrider examples/*
```

I'm not necessarily opposed to that. If you can specify it in the Readme as a breaking change I;m happy to merge it.

**Comment by markspolakovs** [comment]
Sounds good - updated to highlight breaking change.

**Comment by martinhaus** [comment]
Perfect, thank you!

**Comment by martinhaus** [comment]
These changes are part of the v0.3.0 release.

**Pull request merged**
